
TOTAL_CORE_SOURCES += $(DEFAULT_CORE_SOURCES)
TOTAL_USER_SOURCES += $(SOURCES)

objects_tmp_1 = $(TOTAL_CORE_SOURCES:.c=.o)
TOTAL_CORE_OBJECTS = $(addprefix $(DEPENDENCY_DIR)/core/, $(objects_tmp_1:.cpp=.o))

objects_tmp_2 = $(TOTAL_USER_SOURCES:.c=.o)
TOTAL_USER_OBJECTS = $(addprefix $(DEPENDENCY_DIR)/, $(objects_tmp_2:.cpp=.o))

TOTAL_INCLUDE_PATHS = $(DEFAULT_INCLUDE_PATHS) $(INCLUDE_PATHS)

TOTAL_COMPILER_FLAGS = $(DEFAULT_COMPILER_FLAGS) $(COMPILER_FLAGS) 
TOTAL_LINKER_FLAGS_ELF = $(DEFAULT_LINKER_FLAGS) $(LINKER_FLAGS)
TOTAL_LINKER_FLAGS = $(DEFAULT_LINKER_FLAGS) $(LINKER_FLAGS)

PROGRAM_CORE_AR = $(DEPENDENCY_DIR)/$(PROGRAM).core.a
PROGRAM_ELF = $(DEPENDENCY_DIR)/$(PROGRAM).elf
PROGRAM_HEX = $(DEPENDENCY_DIR)/$(PROGRAM).hex

all: dps_dir $(PROGRAM_HEX) dps_dir
	@echo "done"

$(PROGRAM_HEX): $(PROGRAM_ELF)
	$(OBJCOPY) -O ihex -R .eeprom $(PROGRAM_ELF) $(PROGRAM_HEX)

$(PROGRAM_ELF): $(PROGRAM_CORE_AR) $(TOTAL_USER_OBJECTS)
	$(LINKER) $(TOTAL_LINKER_FLAGS_ELF) $(PROGRAM_CORE_AR) $(TOTAL_USER_OBJECTS) -L$(DEPENDENCY_DIR) -o $(PROGRAM_ELF)

$(PROGRAM_CORE_AR): $(TOTAL_CORE_OBJECTS)
	$(ARCHIVER) rcs $(PROGRAM_CORE_AR) $(TOTAL_CORE_OBJECTS)

$(DEPENDENCY_DIR)/%.o $(DEPENDENCY_DIR)/core/%.o: %.c
	$(COMPILER_C) $(TOTAL_COMPILER_FLAGS) $(addprefix -I, $(TOTAL_INCLUDE_PATHS)) -c $< -o $@
$(DEPENDENCY_DIR)/%.o $(DEPENDENCY_DIR)/core/%.o: %.cpp
	$(COMPILER_CXX) $(TOTAL_COMPILER_FLAGS) $(addprefix -I, $(TOTAL_INCLUDE_PATHS)) -c $< -o $@

dps_dir:
	@mkdir -p $(DEPENDENCY_DIR)/core

clean:
	rm -rf $(DEPENDENCY_DIR)
